### ISSUE TITLE
Consolidate site

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#1]
- [x] Remove the reverse proxy to brandnewcongress.github.io
- [x] Move all the pages from brandnewcongress.github.io repo into this repo as markdown pages
- [x] Add a react component that can read markdown templates and apply our basic styling to it, giving people the ability to use Github as a basic CMS via markdown. The idea here is to have a folder called /website/static-pages. This folder will contain pages that are just markdown. The website will have a default route that will just load files from this folder and style it using the site's styles.  We need a special tag to enable listing calls.
- [x] Remove all pages on Nationbuilder and put them into /static-pages

**Comment by saikat** [comment]
Benefit of moving stuff into this repo is a) way easier to maintain the code and b) we can make it a nice slick spa and do nicer JS effects and such.  Benefit of putting things all in NB is we can use some of NB's built-in features

**Comment by saikat** [comment]
Should be noted - Nationbuilder pages will still be accessible on go.brandnewcongress.org/<page>, but we just won't spend a bunch of time making sure NB themes are updated and consistent.  So this way, if people need to make a quick dynamic page using nationbuilder, they still can -- it will just not look good.  And then we can move it in to the main website and style it when we get the time to.

**Comment by ryankopf** [comment]
Items 1 through 3 are started in #70

**Comment by saikat** [comment]
Closing this and splitting it up into more specific tasks that need to happen now that the initial consolidation is done.
