### ISSUE TITLE
Move all the Google docs over to the site

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#1]
- [ ] https://docs.google.com/document/d/1_Aob44aXGpc6OVOxzLNMSW-9_Hs7m5nghKYBGoeuUlE/edit
- [ ] https://docs.google.com/document/d/1sCFs5hqitbXBBqXxU6NULDyvydXqm-ALOqW21dv9P9k/edit
- [ ] https://docs.google.com/document/d/1Op0OaZNuykCJckSCn4vABDEr4VEdTrMeTsPCZFNSJo4/edit

**Comment by chadwickmeyer** [comment]
Merged with https://github.com/BrandNewCongress/website/issues/21
