### ISSUE TITLE
Links from http://brandnewcongress.org/teams result in 404 error

### ISSUE THREAD

**Issue by JDL440** [BrandNewCongress/website#102]
Go to http://brandnewcongress.org/teams
Click on Calendar
404 error shown

The same is true for most of the links.

It looks like maybe these links should go to http://go.brandnewcongress.org/teams?

**Comment by saikat** [comment]
We should fix this by just moving the teams page off nationbuilder. This is happening in #79 .  @jakerockland are you able to move /teams over as well?

**Comment by jakerockland** [comment]
Just got started on #107 moving all of the nation builder files over. Plan is to try to finish this up by end of week.

**Comment by saikat** [comment]
Thank you!  Also are you in our slack yet?

**Comment by jakerockland** [comment]
I'm not yet, no, would love an invite though!

**Comment by saikat** [comment]
This should be fixed now.  Thanks @jakerockland, merged in your PR!
