### ISSUE TITLE
petitions and take_action pages have boiler plate text

### ISSUE THREAD

**Issue by JDL440** [BrandNewCongress/website#103]
http://go.brandnewcongress.org/petition 

To change this content, click "Edit this page" in the Supporter Nav on the right,
or from your Control Panel navigate to Websites > [take_action] > Subpages > [petition] > Petition settings > Intro/Content.

http://go.brandnewcongress.org/take_action

To change this content, click "Edit this page" in the Supporter Nav on the right,
or from your Control Panel navigate to Websites > [take_action] > Content.

**Comment by saikat** [comment]
Yeah those pages shouldn't exist.  The template for the teams page got messed up and a bunch of nationbuilder cruft got put into it.  Closing this issue for now in favor of #102
