### ISSUE TITLE
Report that brandnewcongress.org/tour is not working properly on mobile

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#105]
The report is that the tour page doesn't work when you zoom in on a state on mobile.  We need someone to verify this and fix it!

**Comment by cyranix** [comment]
Here's the behavior I'm seeing on Android 6:

* Zoom in on map:
![screenshot_2016-08-15-20-31-13](https://cloud.githubusercontent.com/assets/161077/17687190/f062ccae-6327-11e6-85b7-8d83152d3cf4.png)
* Click on a state, and the viewport shifts to an unhelpful location — this is exacerbated depending on zoom level and device orientation:
![screenshot_2016-08-15-20-31-29](https://cloud.githubusercontent.com/assets/161077/17687612/62a92fe4-632b-11e6-8316-c7c78947af28.png)
* Here's a more desirable viewport for the same state:
![screenshot_2016-08-15-20-31-53](https://cloud.githubusercontent.com/assets/161077/17687625/7fad5106-632b-11e6-8af6-7d989fba294b.png)
* It takes a bit of scrolling to get over to the map reset icon — and if you've never used the map before, you wouldn't know to scroll and look for it:
![screenshot_2016-08-15-20-32-14](https://cloud.githubusercontent.com/assets/161077/17687649/b9648d4c-632b-11e6-8bda-b565d8531e22.png)

Seems like some viable improvements might include

* anchoring the map reset icon so it's always visible regardless of map panning
* calculating the zoom/pan relative to the viewport

**Comment by cyranix** [comment]
That said, the tap-to-filter functionality does work, and everything readjusts properly upon zooming out again. The mobile experience on `/tour` overall isn't resilient to zooming in right now, so I wouldn't deem this an urgent issue.

**Comment by saikat** [comment]
Yeah that sounds right to me too.  Maybe it'll be more important to get this right for #98 .  Going to close this issue.
