### ISSUE TITLE
Add auto geolocation to tour page with fallback ZIP code form

### ISSUE THREAD

**Issue by danblaker** [BrandNewCongress/website#114]
http://brandnewcongress.org/tour
Assuming the intent for this page is to have me take action and RSVP to a local event, the page should make it as easy as possible to find my city. To that end, the page should allow me to auto-detect my location or enter my ZIP code, then surface my closest event at the top of the page.

**Comment by saikat** [comment]
Good idea.  As the tour is actually coming to a close fairly soon, I'm going to merge this into #98, which is going to be the longer term map we use.  Thanks!
