### ISSUE TITLE
Show all city names when zoomed in

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#12]

**Comment by patrickmcelwee** [comment]
Is this still needed? 

I worked on a fix for this, but I need to do some collision detection (I think) to make sure the labels are readable. Right now, it creates situations like this:
<img width="850" alt="screen shot 2016-06-27 at 12 11 47 am" src="https://cloud.githubusercontent.com/assets/808015/16368389/e05c4d6a-3bfb-11e6-830f-fcb39546ad60.png">

**Comment by saikat** [comment]
Would be a nice to have, but not as important now since zooming in filters
the list of cities below the map.  I wouldn't try too hard on it.
