### ISSUE TITLE
fix top-nav links from local event pages

### ISSUE THREAD

**Issue by etolpygo** [BrandNewCongress/website#123]
from a local event page, such as http://go.brandnewcongress.org/san_francisco_brand_new_congress_organizing_kick_off
top-level navigation links to The Goal, The Plan, and FAQ do not work

**Comment by haleyzink** [comment]
That is because it is sending to go.brandnewcongress.org instead of brandnewcongress.org - looking into how to fix now.

**Comment by cyranix** [comment]
This should now be resolved! Thanks for reporting.

(There's a separate issue for the fact that the Contribute button is unresponsive.)
