### ISSUE TITLE
Reports that signing up from phone causes issues

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#124]
Some reports of invalid email address being reported.

**Comment by cyranix** [comment]
To clarify: people are still able to sign up, but the email in their registration info is invalid? Or they are being shown a validation error for "invalid email address" when they try to register by phone?

**Comment by saikat** [comment]
I think the issue is actually that people are putting spaces in their info
and not noticing.  It's just happening to happen more via phone.  Adding
some code to strip spaces would help.
