### ISSUE TITLE
Change of wording on The Goal (/goal)

### ISSUE THREAD

**Issue by tdlm** [BrandNewCongress/website#125]
> We want to end the poverty and suffering of tens of millions of Americans, reverse the effects of climate change so the world does not end by 2100

This sounds a bit dramatic. The world won't end, but our ability to inhabit it might.

**Comment by cyranix** [comment]
Maybe something like "reverse the effects of climate change so we can pass on a healthy planet to future generations"?

/cc @haleyzink

**Comment by haleyzink** [comment]
we could try "reverse the effects of climate change so the planet is still inhabitable in 100 years" 
/cc @cyranix
