### ISSUE TITLE
Add a section on front page that lets incumbents get in touch with us

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#13]
Something like 'Are you an elected official who likes our platform? Get in touch with us to work with us.'

**Comment by chadwickmeyer** [comment]
@saikat 

**Design**
- How prominent do you want this? 
- Do you really think many existing politicians are going to come to the site and sign up? And for the few that do, don't you think they will just send an email through the contact us link? Thinking about optimizing for conversion goals, I just wonder how much you want to pack on the front page for a very tiny audience.
- Looking at the home page, I'm not sure where to sneak this in. We already have a "join" form. Perhaps we could just add a checkbox under that that says, "I am an incumbent and I want to talk." 

**Functionality**
- Do you want this to go to a specific page with more info, or just be an email submission form
- If a submission form, do you just want their email, and where do you want it to submit this to (api URL and property names).
