### ISSUE TITLE
Rearrange homepage 'All The Specifics' section.

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#14]

**Comment by chadwickmeyer** [comment]
@saikat Please provide more details. 
1. Link to Form (is this a form on the existing site, or a third party form that needs to be moved over)
2. What do you want to appear on the "support" and "home" page (just a link or entire form), and where do you want it to appear.

**Comment by saikat** [comment]
So this is related to #5.  I would do #5 first.  And then I would do this on the homepage: 

1) Change 'All The Specifics' to instead say 'Get Involved'
2) Have the three big buttons on it link to:
* Nominate a Local Leader -> /nominate (the new /nominate link described in #5 
* Donate
* Tell us how you can help -> https://goo.gl/forms/CGeULYdVgKTnW72D2

**Comment by chadwickmeyer** [comment]
The code for this has been staged and committed. Daniela is redesigning the buttons and then we'll push live.

**Comment by chadwickmeyer** [comment]
This has been completed.
