### ISSUE TITLE
Term Limits, Redistricting, and other Election Reforms need to be a requirement for representatives.

### ISSUE THREAD

**Issue by spalmer8** [BrandNewCongress/website#149]
To decrease the polarization of American citizens, we need to implement election reform; term limits being at the top of the list.  It is not enough to remove corporate monies, we need to ensure term limits are put back into place, a check in place that corrupt politicians will be removed by law.  We need folks who are nominated or decided to run on this platform to make a commitment to true election reform.  This information needs be written into "The Plan" section.

**Comment by saikat** [comment]
Redistricting is something that state legislatures unfortunately control.  But election reform is something we do plan to add to the plan.  Thanks for the suggestions!  I'm going to close this issue for now as this is not really a code-related bug, but we are definitely on board with electoral reform and going to be updating our plan further.
