### ISSUE TITLE
Simplify the nomination form

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#15]
* Nominator Name/E-mail/Phone
* Nominee Name/E-mail/Phone
* Nominee City/State/CD
* Nominee Facebook/LinkedIn/Twitter
* Why would this person make a good candidate? Tell us about their background, work experience, leadership experience, public speaking abilities, political views, and anything else you think we should know.
* Links about your candidate. Include personal homepage, youtube videos of them speaking, etc.

**Comment by saikat** [comment]
Model it after https://justicedemocrats.com/nominate/.  Submit the new fields as nomineeProfile and nomineeLinks.

**Comment by chadwickmeyer** [comment]
The changes to the form have been made, to reflect the simpler version requested.
