### ISSUE TITLE
delete old/unused branches

### ISSUE THREAD

**Issue by marwahaha** [BrandNewCongress/website#166]
I want to help! Perhaps we can delete branches from PRs that have merged.

What do you think? @saikat

**Comment by saikat** [comment]
Yeah, no reason not to I suppose, but I don't think their existence hurts us too much.  Are you in the Slack by the way?  I'm going to try to post some projects that we need help with in the next week in there!

**Comment by saikat** [comment]
(Going to close this issue though, but really glad you want to help and welcome aboard!)
