### ISSUE TITLE
Improve the styling of the Event Details popup

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#17]
As part of this, Fix style of RSVP button in the popup when clicking a dot

**Comment by jordanstreiff** [comment]
<img width="575" alt="detail-styling" src="https://cloud.githubusercontent.com/assets/2907541/15561924/a5cec8a4-22c8-11e6-9f57-8175edd50b38.png">

Sufficient for now?

**Comment by saikat** [comment]
Yeah that works I think.

**Comment by saikat** [comment]
Feel free to open a PR!

**Comment by jordanstreiff** [comment]
Will do - going to push up after I leave work today.

**Comment by patrickmcelwee** [comment]
I think this is finished, right? Close this ticket?

**Comment by saikat** [comment]
Yup!
