### ISSUE TITLE
Make signups go directly into NationBuilder

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#19]
Use the API, but to do that we need an API key. http://nationbuilder.com/developers_apply

**Comment by frankimbur** [comment]
I want to make sure I understand the task. Nationbuilder apparently makes developers create 3 examples that use their API before they will issue a key. So: we need someone to write the 3 examples so we can get our own API key? If that's the case, I can do this I'm familiar with APIs... Thanks!

**Comment by saikat** [comment]
Great!  Yeah we requested an API key a couple days ago, hopefully we'll get
it soon.  Once we do I'll ping you.

**Comment by frankimbur** [comment]
OK standing by

**Comment by saikat** [comment]
@frankimbur Want to take a shot at getting the API key?  I think the person who was attempting to get it for us last time didn't end up finishing.

**Comment by frankimbur** [comment]
@saikat:  Sorry I didn't get back to you to confirm your last message - I can see in another thread that @evanhl has been tasked on this, so I'll give him a chance to make some progress and stand by to pitch in if his efforts stall....
