### ISSUE TITLE
Port Over External Resources and Forms

### ISSUE THREAD

**Issue by chadwickmeyer** [BrandNewCongress/website#21]
There are additional forms and resources that are currently hosted externally (mostly on Google docs), which need to be ported over to the website.

The forms need to connect to an API, which means someone (with the guidance of @saikat) need to create the API connection point and variables. Update this list with the URL, and list of variables for each form field as they are created. If someone builds the form first, create the field names based on existing standards for other fields (camelCase) and add the fields here for the API builder.

Whenever a resources moved over, the codebase needs to be searched to update links to go to the new local page.

Forms
=====

District Research
https://docs.google.com/forms/d/e/1FAIpQLSe8CfK0gUULEVpYFm9Eb4iyGOL-_iDl395qB0z4hny7ek4iNw/viewform

Suggest Local Connector
https://docs.google.com/forms/d/e/1FAIpQLSceYguZI_gngXf7dLOXN6xUkLRNsYfn0b2v-aDEvZKPH-j1dQ/viewform

Resources
========

Organize Locally (just local files, probably should be zipped and provided as a PDF download)
https://docs.google.com/document/d/1Op0OaZNuykCJckSCn4vABDEr4VEdTrMeTsPCZFNSJo4/edit

Candidate Nomination Guide:
https://docs.google.com/document/d/1_Aob44aXGpc6OVOxzLNMSW-9_Hs7m5nghKYBGoeuUlE/edit

Plan to Rebuild America (keep external ATM since it's changing a lot)
https://docs.google.com/document/d/1sCFs5hqitbXBBqXxU6NULDyvydXqm-ALOqW21dv9P9k/edit

**Comment by chadwickmeyer** [comment]
@ben-pr-p is this something you could do? We could start with the District Research and Suggest Local Connector forms, following the same naming standards as existing API requests. Just get me a list of the fields and I knock up the forms in a jiffy.

**Comment by ben-pr-p** [comment]
I could do this after setting up the backend for the dashboard which I'll do after the 11th (finishing finals)

**Comment by chadwickmeyer** [comment]
@ben-pr-p awesome. If you could also first do this one single field addition, that would be quick and awesome:
https://github.com/BrandNewCongress/website/issues/23
