### ISSUE TITLE
Move Justice Democrats over to SiteTheory

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#25]
Make sure JD site shares the same nomination and volunteer forms, so we can easily update in one location.

**Comment by chadwickmeyer** [comment]
The site has been migrated to the Sitetheory platform using the shared BNC "Organizer" content types. This site should be reviewed and approved so we can go live. I advise pointing beta.justicedemocrats.com to the same DNS as brandnewcongress.org if you want to confirm the site on the LIVE server.

Required Steps to Go Live:

1. @saikat provides SSL certificate for server.
2. Writing team provides us with the JD FAQ text.
3. Point DNS for justicedemocrats.com to the same DNS that brandnewcongress.org is pointed.

**Comment by chadwickmeyer** [comment]
This has been completed.
