### ISSUE TITLE
Fix Justice Democrats special skills form to submit time availability

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#26]

**Comment by chadwickmeyer** [comment]
If we are moving the JD site to the same Sitetheory platform as BNC, this will be solved at that time.

**Comment by saikat** [comment]
Yeah agreed.  That's partly why I've started listing JD issues in this repo.

**Comment by chadwickmeyer** [comment]
K, so I'll close this ticket then and just make a note on the migration ticket.

**Comment by saikat** [comment]
Is the migration ticket an issue in this website somewhere?

**Comment by chadwickmeyer** [comment]
Yes. You created this issue and I updated with your note:
https://github.com/BrandNewCongress/website/issues/25
