### ISSUE TITLE
Add new privacy policy to both JD and BNC websites

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#27]

**Comment by chadwickmeyer** [comment]
Page added to the BNC site: https://brandnewcongress.org/privacy
Link added to footer (under "contact us" for the time being).

**Question**
@saikat I'm just going to reuse/modify the Justice Democrats content.
https://justicedemocrats.com/privacy/

**Comment by chadwickmeyer** [comment]
This has been completed. https://brandnewcongress.org/privacy

**Comment by saikat** [comment]
Re-opening this as we have final wording for the privacy policy from lawyers.  We also need to update the JD website with it.  Chad, I forwarded you the privacy policy in an email (it's a word doc unfortunately so can't link to it here).

**Comment by chadwickmeyer** [comment]
The privacy policy has been updated.
