### ISSUE TITLE
Make Justice Democrats volunteer link to BNC volunteer section

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#29]

**Comment by chadwickmeyer** [comment]
We are [migrating the JD site](https://github.com/BrandNewCongress/website/issues/25) to be on the BNC platform, but they will be separate sites (with slightly separate wording). Which sort of integration of forms do you prefer:

1) Link Out: JD forms link to BNC (so people know they will be contacted by BNC staff for organizing).
2) Local: JD forms will reside on JD site, so people stay within the JD brand (we'll share code behind the scenes to make sure it's easy to maintain).

**Comment by chadwickmeyer** [comment]
The JD site has been migrated to the Sitetheory platform using the shared BNC "organizer" content types on both sites. So this makes it easy to update/maintain in one place now. Hurray. This will be reflected on the live site when the DNS switches over.
