### ISSUE TITLE
Update platform on website with new version that Zack wrote

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#31]

**Comment by chadwickmeyer** [comment]
Is this the new platform? Or is there some other document that we need to reference to update:
https://brandnewcongress.org/plan
If so, please provide link to new platform Google Doc.

**Comment by danielameyer** [comment]
I haven't received the new platform yet and believe that the Plan page is mostly original to what we had when launched. I think when the platform is ready we'll install a more official platform page. This issue appears to be assigned to Saikat, so we'll hold on this until he's ready to roll.

**Comment by chadwickmeyer** [comment]
We were given access to the entire platform folder. But does this mean that the platform is ready? Is there a single document that we should import to the new site?
