### ISSUE TITLE
Clean up extraneous console.log statements

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#34]

**Comment by jordanstreiff** [comment]
Looks like someone already got to this. Couldn't find any stray logs in master.

**Comment by saikat** [comment]
Try doing a quick find all for console.log in the project?

**Comment by jordanstreiff** [comment]
Hmmm... I did, not seeing anything. Also not seeing the same statements I was seeing in the console earlier today.

**Comment by saikat** [comment]
Ok nice will close
