### ISSUE TITLE
Fix spacing between event name and rsvp buttons 

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#39]

**Comment by traviskaufman** [comment]
@saikat can take if no one's working on it

**Comment by saikat** [comment]
Sweet thanks!

**Comment by traviskaufman** [comment]
@saikat per the convo in #45 should the event name + button be centered on screen or would you rather should the rsvp button be at most X units away from the title text?

**Comment by traviskaufman** [comment]
@saikat Three different styling options, let me know which one you like best:

## Option 1

`max-width` set on eventInfo

<img width="1428" alt="screen shot 2016-06-04 at 5 10 05 pm" src="https://cloud.githubusercontent.com/assets/1185269/15802230/b24a36c8-2a79-11e6-8ebc-28af80243377.png">

## Option 2

`max-width` set on event list, centered

<img width="1440" alt="screen shot 2016-06-04 at 5 11 37 pm" src="https://cloud.githubusercontent.com/assets/1185269/15802231/b74858d0-2a79-11e6-86bb-7b2922e68aea.png">

## Option 3

`max-width` set on event list, left-aligned

<img width="1143" alt="screen shot 2016-06-04 at 5 26 09 pm" src="https://cloud.githubusercontent.com/assets/1185269/15802233/c496cd0a-2a79-11e6-922f-42d45dda42a0.png">


All 3 of these options don't set a max-width on the containing site so it scales to all viewports. WDYT?

**Comment by traviskaufman** [comment]
Another option would be to use `display: table` and make it so the RSVP button is always correctly aligned directly to the right of the event info.

**Comment by saikat** [comment]
Actually, I'm messing with the site now and I'm not sure this is a problem
anymore since Rapi made the 3 column layout.

**Comment by traviskaufman** [comment]
np; feel free to close it then! I fixed some react warnings and lint issues as part of my work here so I can make a PR for that.

**Comment by traviskaufman** [comment]
per offline convo, going with option 3 above
