### ISSUE TITLE
Menu button on Go.Brandnewcongress.org does not work on mobile. 

### ISSUE THREAD

**Issue by JayMatthew** [BrandNewCongress/website#39]
Should be removed or made to work.

**Comment by JayMatthew** [comment]
I'm on android using Chrome for some more detail.

**Comment by chadwickmeyer** [comment]
@saikat  What exactly is this website: go.brandnewcongress.org
It looks like just the old website, with missing images and bad links. 
This sub domain should either be deleted, forwarded to main domain, or something needs to change on this site to provide unique value (and not confuse visitors that find it).

**Comment by danielameyer** [comment]
I think that an email was accidentally sent out with that old URL rather than the new one so people noticed that things weren't working. That domain probably just needs to redirect. I'm 99% certain there is no reason to send visitors there.

**Comment by chadwickmeyer** [comment]
@JayMatthew how did you find that URL? 

We probably also need to:
- Make sure the page that was linked to this bad URL is updated.
- Redirect that to the home page (in case this is in Google). 
    - @saikat I've asked ben if he has access to that domain, but if you want to give me access too, I can take care of these sorts of things.
- Cancel the hosting for that old site (if necessary to save money) 
    - @saikat you will know if/how to do this.

**Comment by JayMatthew** [comment]
It was found via an email link. Lemme find it.

**Comment by JayMatthew** [comment]
The naked link at the bottom of the last email I got reads
go.brandnewcongress.org and the logo at the bottom links to
go.brandnewcongress.org.

**Comment by chadwickmeyer** [comment]
Thanks. That was a mistake. We'll find the people who did that and punish them :D

**Comment by JayMatthew** [comment]
Make it harsh and swift.

**Comment by chadwickmeyer** [comment]
Done. How's that for swiftness.

**Comment by JayMatthew** [comment]
Maybe a bit too swift.

**Comment by JayMatthew** [comment]
The logo at the bottom of my last email still links to
go.brandnewcongress.org. Even though it's forwarding now I just thought I
should point that out.

**Comment by chadwickmeyer** [comment]
Based on What Saikat said, that subdomain appears to function as a redirect to track clicks in Nation Builder. So I *think* that's intentional.

**Comment by chadwickmeyer** [comment]
But I will leave this ticket open because the actual old website is still appearing at: go.brandnewcongress.org and at the very least it should just be a blank page with the logo and a link that says "Please visit our main website."

**Comment by danielameyer** [comment]
Right! They are doing one off call to action forms like this http://go.justicedemocrats.com/page/s/letter-to-keith-ellison

But is it possible to have http://go.justicedemocrats.com redirect to the main site but still use direct URLs to get people to these extra forms? I know my ignorance is showing.

**Comment by saikat** [comment]
go.justicedemocrats.com is different from go.brandnewcongress.org.  @ben-pr-p could you check that other than e-mail links using go.brandnewcongress.org for link tracking (which we can switch to brandnewcongress.nationbuilder.com if we get rid of the CNAME), we aren't using that url for anything else?

**Comment by saikat** [comment]
@ben-pr-p I'd like to remove the homepage for go.brandnewcongress.org and close this out.  How close are we to that you think?
