### ISSUE TITLE
Create different texts that fade in and out under 'Elect a Brand New Congress'

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#4]

**Comment by chadwickmeyer** [comment]
@saikat Please provide the general idea for the messaging that you want to communicate. We'll massage the text and make it happen.

**Current Text:**
WE’RE RUNNING 400+ CANDIDATES IN A SINGLE CAMPAIGN TO REBUILD OUR COUNTRY.

**Possible Additional Text:**
- WE HAVE A PLAN TO INCREASE WAGES, REMOVE BIG MONEY, AND PROTECT YOUR RIGHTS.
- ELECTING A ROTATION OF HONEST AMERICANS WHO ARE LEADERS IN THEIR COMMUNITY.
- JOIN US TO ELECT A BRAND NEW CONGRESS THAT WILL SERVE YOUR INTERESTS.

**Comment by danielameyer** [comment]
So I think the plan is to keep the messaging "Elect a brand new congress
that works" but then have the "for all Americans" appear followed by "for
all workers" followed by "for all [ ]". That sort of thing. We do probably
need a list of 5 words to replace "Americans".

**Comment by chadwickmeyer** [comment]
Okay, I think we can probably decide what those are. If Saikat wants to contribute he can, but I think he is happy for us to be creative.
