### ISSUE TITLE
Have a way to detect and not allow submissions for self nominations

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#40]
People can obviously get around this, but I think it'll stop a lot of the self nominations we get if we flag it when people try.

**Comment by chadwickmeyer** [comment]
That would be easy. Would you just want to check that the name and/or email of the nominator is the same as the nominee? Or do you have another idea.

Also, we could make it much more clear: "Please do NOT nominate yourself." Would you want something more clear above that section?

**Comment by saikat** [comment]
yup, the first.  and also make it clearer but maybe with a nicer message.

**Comment by chadwickmeyer** [comment]
Ok, I've add this and it's working on the dev server. We'll push it live when the changes to core are pushed live next time.

**Comment by chadwickmeyer** [comment]
These changes have been pushed to production and tested.
