### ISSUE TITLE
Missing links to social media presence

### ISSUE THREAD

**Issue by yihpin** [BrandNewCongress/website#41]
On the main page there are links to share on social media, which are nice, but would be nice to see links to our social media pages as well so people can start interacting directly on social media.

**Comment by nasimthompson** [comment]
Suggesting social media icons along bottom of WEB and EMAIL pages/templates link as follows:
Facebook: https://www.facebook.com/brandnewcongress
Twitter: https://twitter.com/BrandNew535
Redit: https://www.reddit.com/r/BrandNewCongress/
ActBlue:https://secure.actblue.com/contribute/page/brandnewcongress

**Comment by itstriz** [comment]
Would this be replacing the share icons or be in addition to the share icons?

**Comment by saikat** [comment]
It would be changing the URLs on the existing share icons.

**Comment by itstriz** [comment]
got it.

**Comment by itstriz** [comment]
Submitted a pull request in the static repo.

**Comment by ryankopf** [comment]
Is this fixed? There appear to be icons linking to the right places as suggested.

**Comment by nasimthompson** [comment]
yes
