### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#43]
AGPL v3

**Comment by itstriz** [comment]
Do you just want the license added as a new page and linked in the footer?  If so, I'll take it.

**Comment by saikat** [comment]
No need to link anything -- literally just need to add a LICENSE file to this github repo (AGPL-3.0 is what Id like to make it).  Thanks!

**Comment by itstriz** [comment]
K. I'll do it :dancers:

**Comment by itstriz** [comment]
Submitted pull request.

**Comment by saikat** [comment]
Closed!
