### ISSUE TITLE
Make the zoom out button more obvious

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#47]
I think just the blue button in bottom left corner is too hidden

**Comment by ryankopf** [comment]
Referring clicking on a state on http://brandnewcongress.org/tour

This appears to be in NationBuilder? I can't find it to edit in source material.
Adding/changing to .c9  width: 50px;height:50px;margin: 10px; will make it much more obvious.

**Comment by saikat** [comment]
Closing this for now in favor of #98
