### ISSUE TITLE
Rearrange support page

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#5]
This is more of a rejiggering of the support page.  I'd like to have it model the 'act now' box on justicedemocrats.com

So support will have these sections:
Nominate -> /nominate (which will now be just the form with instructions at the top exactly like on https://justicedemocrats.com/nominate)
Donate
Research to find a candidate -> /candidate-research (the current /nominate).
Tell us how you can help -> Goes to the special skills form
Tell us about your Congressional District -> Goes to https://docs.google.com/forms/d/e/1FAIpQLSe8CfK0gUULEVpYFm9Eb4iyGOL-_iDl395qB0z4hny7ek4iNw/viewform
Connect us with people we should talk to -> https://docs.google.com/forms/d/e/1FAIpQLSceYguZI_gngXf7dLOXN6xUkLRNsYfn0b2v-aDEvZKPH-j1dQ/viewform
Organize Locally
Join a Call
Donate

**Comment by chadwickmeyer** [comment]
This has been completed and approved by Saikat.
