### ISSUE TITLE
Clean up all the unformed team pages

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#5]
They need to have a consistent style and not have commenting ability on them

**Comment by jakerockland** [comment]
Trying to get started with this, but I'm a bit confused about how the Nationbuilder platform works. How do I access the pages that reverse proxy to go.brandnewcongree.org?

`  '/teams',
  '/forms',
  '/helpdesk',
  '/talentteam',
  '/eventsteam',
  '/legal_team',
  '/moneyteam',
  '/travelteam',
  '/crmteam',
  '/analytics_team',
  '/web_team',
  '/platformteam',
  '/creative_team',
  '/social_media',
  '/email_team',
  '/pressteam'],`

Also, is the consistent standard moving forward to have these pages in Nationbuilder or as static HTML pages?

**Comment by saikat** [comment]
Standard going forward is to have these be static HTML pages.  I actually
made a thing to be able to have all the static pages just be written in
markdown -- if you take a look at
https://github.com/BrandNewCongress/website/tree/master/src/static/site -
any page you put there will turn into a URL that it  can be accessed as.
Was thinking we'd just transfer the nationbuilder pages into there as well
as the static-site pages.  I can get you Nationbuilder access but you
shouldn't actually need it to get started since we'll just be transferring
those pages into markdown anyway.

**Comment by jakerockland** [comment]
That sounds good to me! I saw the markdown task which made this a bit more clear to me. I actually got started on #79 last night, #101 is a work in progress for this.

**Comment by cyranix** [comment]
@saikat @jakerockland Is there any work left to do on this issue? It looks like this is addressed by #101 and #107. Please update on remaining tasks or close the issue if we're all done here!

**Comment by jakerockland** [comment]
Whoops, yep I believe this is taken care of with #101 and #107. 😄

**Comment by jakerockland** [comment]
There is perhaps some refactoring and minor tweaks that could be made later if we want all of the copy to be very very consistent across team pages, but I made sure to make formatting and general copy the same across them in #101 and #107. I think this can be closed for now 👍
