### ISSUE TITLE
Signup Form should use correct input types

### ISSUE THREAD

**Issue by traviskaufman** [BrandNewCongress/website#50]
Currently email address, phone number, and zip are all set to type `text`. A better strategy might be to have email address set to type [email](https://www.w3.org/TR/html-markup/input.email.html), and have phone nbr and zip set to type [tel](https://www.w3.org/TR/html-markup/input.tel.html). This will make entering information a lot easier on mobile devices and will help with a11y and browser semantics (e.g. Chrome's autofill knows how to operate on `≤input type="email">`.

I'm pretty sure that we can use `tel` for zip codes since we can assume we're only dealing with US zips.

**Comment by traviskaufman** [comment]
@saikat happy to take this as well. Also can probably be labeled `newbie-friendly`?

**Comment by saikat** [comment]
Yes to both of those. You'll probably need to change this in the github
pages repo instead of the website repo (hope to have these two be combined
in the near future).

**Comment by saikat** [comment]
@traviskaufman did you end up getting anywhere on this issue?
