### ISSUE TITLE
Cross-Domain Tracking in GA

### ISSUE THREAD

**Issue by kmpcpm** [BrandNewCongress/website#55]
Hi @saikat and @evanhl,

In order to track activity on ActBlue that originated in BNC.org, Google Analytics tracking code needs to be modified in both. ActBlue's is already modified via their platform settings. **Now, the existing GA code on BNC.org must be replaced.** 

The result is that GA will report on both sites in one view and track movement between them as if they were different halves of the same property. Unless there's a special situation, this change will also mean that outbound links from BNC.org to ActBlue won't need to be individually tagged. 

Cross-Domain Tracking must be in place before ecommerce tracking can be enabled. This is the next step in the process of attributing contributions on ActBlue to traffic sources for BNC.org.

The new values are for **'allowLinker', 'require',** and **'linker:autoLink'.** Please use the below code to completely replace the existing GA code for BNC.org:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75845088-1', 'auto', {'allowLinker': true});
  ga('require', 'linker');
  ga('linker:autoLink', ['https://secure.actblue.com'] );
  ga('send', 'pageview');

</script>
```

**Comment by patrickmcelwee** [comment]
This should be done after #70 is merged
