### ISSUE TITLE
Clicking on a dot on mobile should zoom in to the map

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#57]

**Comment by rapicastillo** [comment]
This would be in conflict with #37 (Disable clicking dots on mobile)

**Comment by saikat** [comment]
So to explain a bit further here -- what I was imagining is that on mobile, clicking a dot would no longer show the rsvp pop up (which your fix to #37) did, but it would still do a zoom.  The idea being that whenever you click on a region of the map on mobile, regardless of if your fat finger hits a dot or not dotted region, it zooms in.  Otherwise it will sometimes feel like it just doesn't work.  Not a huge deal though.
