### ISSUE TITLE
Switch all the footers to say us@brandnewcongress.org instead of info@

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#61]

**Comment by gjost** [comment]
Has this already been fixed?  I grepped through the code and saw `us@brandnewcongress.org` in `Footer.jsx` and `SignupForm.jsx` but no occurrences of `info@`.

**Comment by gjost** [comment]
Oops, found an `info@` link in an error message in `brandnewcongress.github.io/assets/js/webservice.js`.  It's not a footer though,

**Comment by ryankopf** [comment]
They were obfuscated in two places. data values and then a JS script too.

I'm working on this (finished but am waiting for pulls to be committed).

**Comment by ryankopf** [comment]
May be fixed in #70

**Comment by saikat** [comment]
This is now done.

**Comment by cyranix** [comment]
@saikat Not seeing any more instances of `info@` — please close! 😄
