### ISSUE TITLE
Include a more prominent "Contribute" button on the front page

### ISSUE THREAD

**Issue by evanhl** [BrandNewCongress/website#67]
Right now we just have a $ icon at the very bottom of the page, which might be confusing to some, especially older visitors. 

From Sandy's comment on Slack:
> Suggestion to the techie people... some of us older folks (who me?) don't recognize those great icons at the bottom for what they are. Someone needs to put a "CONTRIBUTE" button on the page.
On the top...front and center!

**Comment by camgaertner** [comment]
I can try this. Should it actually be front and center? Would probably have to shrink the find your city button and either put one above the other, or side by side. Which is best?

One could also work under the "Get ready for the most beautiful campaign ever." if we move that text up a little.

**Comment by traviskaufman** [comment]
Based on the suggestions we've gotten today I feel like the traditional "3-column marketing site" layout would be good for us, e.g. 

```
| Find Your City Main CTA |
| Sign up CTA | Volunteer CTA | Contribute CTA |
``` 

There seems to have been a lot of discussion on the homepage recently and I know @saikat has also been doing some work on it as well, so maybe it involves a more organized discussion where we can give it a proper design treatment. That being said please feel free to try out something you think might work!

**Comment by saikat** [comment]
Yup I have a work in progress here. Will show you guys once I get on my
computer

**Comment by saikat** [comment]
This was fixed a while back.
