### ISSUE TITLE
Add link to /teams page on home page

### ISSUE THREAD

**Issue by traviskaufman** [BrandNewCongress/website#68]
Mirrored from https://github.com/BrandNewCongress/welcome/issues/16

> There is no link to get to www.brandnewcongress.com/teams from the main website at www.brandnewcongress.com.
> 
> I only just found out about it now because a pollworker called and told me about it. I don't know who's in charge of the website, but it would be trivial to add it, and it would really help us in finding people to volunteer! I've gone to the website many times but only found links to physical gatherings.
> 
> This needs to be done as soon as possible.
- @benisch2

**Comment by traviskaufman** [comment]
cc @saikat Any ideas on where to place this? Footer and/or call-to-action maybe?

**Comment by ryankopf** [comment]
#70 will add one to the bottom of the homepage.

**Comment by saikat** [comment]
This should be done.
