### ISSUE TITLE
Support for windows dev.

### ISSUE THREAD

**Issue by ryankopf** [BrandNewCongress/website#69]
Windows development requires a few tweaks to make things run. I may try to fix these myself but it's my first time doing any node.js work (I use Ruby and Rails). This is low priority unless there's others on Windows.

==For Windows Only==
package.json
"clean" uses "rm" which is not available on Windows
"postinstall" chokes on the node_env value
"dev-start" needs "--exec ./tools" to be "--exec node ./tools"

Procfile.dev
webpack: node ./tools/babel-run ./webpack/server.js

**Comment by evanhl** [comment]
I wonder if the new Windows bash shell could help: http://www.pcworld.com/article/3050473/windows/heres-how-windows-10s-ubuntu-based-bash-shell-will-actually-work.html

**Comment by camgaertner** [comment]
I think it would. That sounds very useful, but you have to be a beta tester to get it right now unfortunately.

**Comment by ryankopf** [comment]
I believe I have fixed this in Windows in #70. 

I created a node script that will run instead of the old system commands, which will replace the commands with either windows commands or notices. I can now "npm install" and "npm run dev" both of which crashed before.

Someone check and see if it still runs okay on Unix systems.

**Comment by Barbarrosa** [comment]
It would probably be better to use Docker and/or Vagrant on Windows systems. Some (maybe all?) JetBrains IDEs have builtin Vagrant support. Docker tends to be more lightweight, though.

**Comment by Barbarrosa** [comment]
If you do choose a VM route like Docker or Vagrant, I recommend a prod-like environment with some dev tools integrated.

**Comment by saikat** [comment]
If anyone has the time to set up a Docker-based dev environment, that'd be
great!  I've used Vagrant in the past, but Docker seems like it's made some
big strides in the dev department and has the added benefit of letting us
completely simulate our prod and dev envs.  Unless it's somewhat easy to
do, though, it may be a bit overkill for just a website.

**Comment by saikat** [comment]
Closing this for now as it hasn't come up since.
