### ISSUE TITLE
Fix link to sign-up on about page

### ISSUE THREAD

**Issue by patrickmcelwee** [BrandNewCongress/website#71]
Hi Saikat - this is Patrick from Durham - taking a look at how I can start helping out. It was great to meet you guys.

The "please sign up" link on the /about page is broken. Small pull request coming ...

**Comment by saikat** [comment]
This should be fixed now!  Thanks @patrickmcelwee, sorry about the delay commenting on this one.  Are you in our Slack by any chance? You can get an invite on http://www.progcode.co/.

**Comment by patrickmcelwee** [comment]
Sorry, just saw your comment (from over a month ago!) on Slack. I hadn't signed back in, but I'm signing up over on progcode now. Thanks!
