### ISSUE TITLE
404 page links redirect to a bad page

### ISSUE THREAD

**Issue by rapicastillo** [BrandNewCongress/website#74]
To re-produce:
1. I went to http://go.brandnewcongress.org/events
2. Then Clicked on **Find an Event**
3. Bad page, was redirected to http://go.brandnewcongress.orgbrandnewcongress.org/tour

**Comment by cyranix** [comment]
@rapicastillo — It seems like this no longer reproduces, as the URL in step 1 doesn't exist. Closing this issue, but if you see a similar behavior still, do let us know.
