### ISSUE TITLE
Move remaining nationbuilder pages into src/static/site

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#78]
These are all the pages listed on https://github.com/BrandNewCongress/website/blob/master/src/server/index.js#L26.  We basically need to go to those pages and turn them into markdown pages that go in the static site dir.

**Comment by jakerockland** [comment]
Starting on this.

**Comment by jakerockland** [comment]
This is finished in #107

**Comment by saikat** [comment]
Also done by @jakerockland, thanks!  @jakerockland, are you in our Slack yet? You can get an invite from http://progcode.co/ and I'll make sure you get added in.
