### ISSUE TITLE
Move remaining static site pages into src/static/site

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#79]
- [ ] Move the pages listed on https://github.com/BrandNewCongress/website/blob/master/src/server/index.js#L54 into the static site dir
- [ ] Remove the legacySite middleware
- [ ] Remove the static-site directory

**Comment by jakerockland** [comment]
I'm starting this one.

**Comment by jakerockland** [comment]
This is almost finished!

**Comment by saikat** [comment]
Done by @jakerockland, thank you!
