### ISSUE TITLE
Create a map that events can be posted to

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#87]
We need to expand the map at /tour to make a map anyone can post to. @rapicastillo are there plans to make Progressive Events in a way that specific orgs can use the same map to just list their own events?

**Comment by rapicastillo** [comment]
Yes. ProgressiveEvents is planning on going about creating a map for groups. Do you have the NB API keys?

**Comment by saikat** [comment]
Yes I do -- I can add you to our Nationbuilder account and you can grab
them from there.

**Comment by rapicastillo** [comment]
That would be great.

**Comment by saikat** [comment]
Going to close this and merge it into #98
