### ISSUE TITLE
Fix Hawaii event

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#9]
The hawaii event is not showing up on the map -- doing 'this.projection()' on its lat/lng results in a null coord value in USMap.jsx.  See what happens if you remove this line:

```
if (coord === null) {
    return ''
}
```

**Comment by rapicastillo** [comment]
I think this should be fixed. --> https://github.com/BrandNewCongress/website/pull/60

**Comment by ryankopf** [comment]
I concur this looks fixed. @saikat
