### ISSUE TITLE
Create /<sept event name> and have it be hidden/ unlisted to be ready for launch 

### ISSUE THREAD

**Issue by haleyzink** [BrandNewCongress/website#99]
- [ ] Nail down / name 
- [ ] Have the site work for pre event, event, and post event
    - so it would have all the materials we are building for pre event (host resources/ party favours etc)
    - it would be able to house the video for during (unless this isn't a good idea?) 
    - and then have the candidate nomination form, candidate litmus test, and vol litmus test

**Comment by saikat** [comment]
Merging this in with the larger issue to keep the discussion in one place!
